name: Deploy to Stage

on:
  push:
    branches:
      - space-io-save-me-stage 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "space-io-spring-rest-dev"
          heroku_email: "jurica1.migac@gmail.com"
          branch: "space-io-save-me-stage"
